// <auto-generated />
using System;
using GameCatalog.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameCatalog.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20250530091909_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameCatalog.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opinion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<DateOnly>("Release_Date")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "RPG",
                            Name = "The Witcher 3: Wild Hunt",
                            Opinion = "Critically acclaimed for its story",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2015, 5, 19)
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Action RPG",
                            Name = "Cyberpunk 2077",
                            Opinion = "Ambitious open-world experience",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2020, 12, 10)
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Survival Horror",
                            Name = "Dying Light",
                            Opinion = "Thrilling zombie survival",
                            Platform = "PC",
                            Price = 49.99f,
                            Release_Date = new DateOnly(2015, 1, 27)
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Sandbox",
                            Name = "Minecraft",
                            Opinion = "Endlessly creative gameplay",
                            Platform = "PC",
                            Price = 29.99f,
                            Release_Date = new DateOnly(2011, 11, 18)
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Action-Adventure",
                            Name = "Grand Theft Auto V",
                            Opinion = "Massive open-world adventure",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2013, 9, 17)
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Platformer",
                            Name = "Super Mario Bros.",
                            Opinion = "Iconic platforming classic",
                            Platform = "NES",
                            Price = 49.99f,
                            Release_Date = new DateOnly(1985, 9, 13)
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Action-Adventure",
                            Name = "The Legend of Zelda: Ocarina of Time",
                            Opinion = "Timeless adventure masterpiece",
                            Platform = "N64",
                            Price = 49.99f,
                            Release_Date = new DateOnly(1998, 11, 21)
                        },
                        new
                        {
                            Id = 8,
                            Genre = "Puzzle",
                            Name = "Tetris",
                            Opinion = "Addictive and timeless",
                            Platform = "Game Boy",
                            Price = 29.99f,
                            Release_Date = new DateOnly(1989, 6, 14)
                        },
                        new
                        {
                            Id = 9,
                            Genre = "RPG",
                            Name = "Final Fantasy VII",
                            Opinion = "Groundbreaking narrative",
                            Platform = "PlayStation",
                            Price = 49.99f,
                            Release_Date = new DateOnly(1997, 9, 7)
                        },
                        new
                        {
                            Id = 10,
                            Genre = "RPG",
                            Name = "Pokémon Red/Blue",
                            Opinion = "Sparked a global phenomenon",
                            Platform = "Game Boy",
                            Price = 39.99f,
                            Release_Date = new DateOnly(1998, 9, 28)
                        },
                        new
                        {
                            Id = 11,
                            Genre = "Platformer",
                            Name = "Super Mario 64",
                            Opinion = "Revolutionary 3D platformer",
                            Platform = "N64",
                            Price = 49.99f,
                            Release_Date = new DateOnly(1996, 9, 26)
                        },
                        new
                        {
                            Id = 12,
                            Genre = "FPS",
                            Name = "Halo: Combat Evolved",
                            Opinion = "Defined console shooters",
                            Platform = "Xbox",
                            Price = 49.99f,
                            Release_Date = new DateOnly(2001, 11, 15)
                        },
                        new
                        {
                            Id = 13,
                            Genre = "Sports",
                            Name = "Wii Sports",
                            Opinion = "Accessible family fun",
                            Platform = "Wii",
                            Price = 49.99f,
                            Release_Date = new DateOnly(2006, 11, 19)
                        },
                        new
                        {
                            Id = 14,
                            Genre = "FPS",
                            Name = "Call of Duty: Modern Warfare",
                            Opinion = "Set multiplayer standard",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2007, 11, 5)
                        },
                        new
                        {
                            Id = 15,
                            Genre = "RPG",
                            Name = "The Elder Scrolls V: Skyrim",
                            Opinion = "Expansive fantasy world",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2011, 11, 11)
                        },
                        new
                        {
                            Id = 16,
                            Genre = "Battle Royale",
                            Name = "Fortnite",
                            Opinion = "Cultural phenomenon",
                            Platform = "PC",
                            Price = 0f,
                            Release_Date = new DateOnly(2017, 7, 25)
                        },
                        new
                        {
                            Id = 17,
                            Genre = "Action-Adventure",
                            Name = "The Legend of Zelda: Breath of the Wild",
                            Opinion = "Redefined open-world games",
                            Platform = "Switch",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2017, 3, 3)
                        },
                        new
                        {
                            Id = 18,
                            Genre = "Arcade",
                            Name = "Pong",
                            Opinion = "Pioneered video gaming",
                            Platform = "Arcade",
                            Price = 0.25f,
                            Release_Date = new DateOnly(1972, 11, 29)
                        },
                        new
                        {
                            Id = 19,
                            Genre = "Arcade",
                            Name = "Pac-Man",
                            Opinion = "Cultural icon",
                            Platform = "Arcade",
                            Price = 0.25f,
                            Release_Date = new DateOnly(1980, 5, 22)
                        },
                        new
                        {
                            Id = 20,
                            Genre = "Platformer",
                            Name = "Donkey Kong",
                            Opinion = "Introduced Mario",
                            Platform = "Arcade",
                            Price = 0.25f,
                            Release_Date = new DateOnly(1981, 7, 9)
                        },
                        new
                        {
                            Id = 21,
                            Genre = "Fighting",
                            Name = "Street Fighter II",
                            Opinion = "Defined fighting games",
                            Platform = "Arcade",
                            Price = 0.25f,
                            Release_Date = new DateOnly(1991, 2, 6)
                        },
                        new
                        {
                            Id = 22,
                            Genre = "FPS",
                            Name = "Doom",
                            Opinion = "Pioneered FPS genre",
                            Platform = "PC",
                            Price = 39.99f,
                            Release_Date = new DateOnly(1993, 12, 10)
                        },
                        new
                        {
                            Id = 23,
                            Genre = "FPS",
                            Name = "GoldenEye 007",
                            Opinion = "Console FPS benchmark",
                            Platform = "N64",
                            Price = 49.99f,
                            Release_Date = new DateOnly(1997, 8, 25)
                        },
                        new
                        {
                            Id = 24,
                            Genre = "Fighting",
                            Name = "Super Smash Bros. Melee",
                            Opinion = "Competitive classic",
                            Platform = "GameCube",
                            Price = 49.99f,
                            Release_Date = new DateOnly(2001, 12, 3)
                        },
                        new
                        {
                            Id = 25,
                            Genre = "Survival Horror",
                            Name = "Resident Evil 4",
                            Opinion = "Redefined survival horror",
                            Platform = "GameCube",
                            Price = 49.99f,
                            Release_Date = new DateOnly(2005, 1, 11)
                        },
                        new
                        {
                            Id = 26,
                            Genre = "MMORPG",
                            Name = "World of Warcraft",
                            Opinion = "MMO giant",
                            Platform = "PC",
                            Price = 49.99f,
                            Release_Date = new DateOnly(2004, 11, 23)
                        },
                        new
                        {
                            Id = 27,
                            Genre = "Rhythm",
                            Name = "Guitar Hero",
                            Opinion = "Music game revolution",
                            Platform = "PS2",
                            Price = 49.99f,
                            Release_Date = new DateOnly(2005, 11, 8)
                        },
                        new
                        {
                            Id = 28,
                            Genre = "FPS",
                            Name = "BioShock",
                            Opinion = "Immersive storytelling",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2007, 8, 21)
                        },
                        new
                        {
                            Id = 29,
                            Genre = "Puzzle",
                            Name = "Portal",
                            Opinion = "Innovative puzzle design",
                            Platform = "PC",
                            Price = 19.99f,
                            Release_Date = new DateOnly(2007, 10, 10)
                        },
                        new
                        {
                            Id = 30,
                            Genre = "RPG",
                            Name = "Mass Effect 2",
                            Opinion = "Epic sci-fi narrative",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2010, 1, 26)
                        },
                        new
                        {
                            Id = 31,
                            Genre = "Action-Adventure",
                            Name = "Red Dead Redemption",
                            Opinion = "Cinematic Western epic",
                            Platform = "PS3",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2010, 5, 18)
                        },
                        new
                        {
                            Id = 32,
                            Genre = "Action-Adventure",
                            Name = "Batman: Arkham City",
                            Opinion = "Superhero perfection",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2011, 10, 18)
                        },
                        new
                        {
                            Id = 33,
                            Genre = "Action RPG",
                            Name = "Dark Souls",
                            Opinion = "Challenging masterpiece",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2011, 9, 22)
                        },
                        new
                        {
                            Id = 34,
                            Genre = "MOBA",
                            Name = "League of Legends",
                            Opinion = "Esports juggernaut",
                            Platform = "PC",
                            Price = 0f,
                            Release_Date = new DateOnly(2009, 10, 27)
                        },
                        new
                        {
                            Id = 35,
                            Genre = "Party",
                            Name = "Among Us",
                            Opinion = "Social deduction hit",
                            Platform = "PC",
                            Price = 4.99f,
                            Release_Date = new DateOnly(2018, 6, 15)
                        },
                        new
                        {
                            Id = 36,
                            Genre = "Simulation",
                            Name = "Animal Crossing: New Horizons",
                            Opinion = "Charming life sim",
                            Platform = "Switch",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2020, 3, 20)
                        },
                        new
                        {
                            Id = 37,
                            Genre = "Platformer",
                            Name = "Super Mario Odyssey",
                            Opinion = "Joyful 3D platformer",
                            Platform = "Switch",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2017, 10, 27)
                        },
                        new
                        {
                            Id = 38,
                            Genre = "FPS",
                            Name = "Overwatch",
                            Opinion = "Team-based shooter",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2016, 5, 24)
                        },
                        new
                        {
                            Id = 39,
                            Genre = "Action-Adventure",
                            Name = "God of War (2018)",
                            Opinion = "Emotional epic",
                            Platform = "PS4",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2018, 4, 20)
                        },
                        new
                        {
                            Id = 40,
                            Genre = "Metroidvania",
                            Name = "Hollow Knight",
                            Opinion = "Atmospheric indie gem",
                            Platform = "PC",
                            Price = 14.99f,
                            Release_Date = new DateOnly(2017, 2, 24)
                        },
                        new
                        {
                            Id = 41,
                            Genre = "Simulation",
                            Name = "Stardew Valley",
                            Opinion = "Charming farming sim",
                            Platform = "PC",
                            Price = 14.99f,
                            Release_Date = new DateOnly(2016, 2, 26)
                        },
                        new
                        {
                            Id = 42,
                            Genre = "Simulation",
                            Name = "The Sims",
                            Opinion = "Life simulation classic",
                            Platform = "PC",
                            Price = 49.99f,
                            Release_Date = new DateOnly(2000, 2, 4)
                        },
                        new
                        {
                            Id = 43,
                            Genre = "Action RPG",
                            Name = "Diablo II",
                            Opinion = "Addictive loot-driven RPG",
                            Platform = "PC",
                            Price = 49.99f,
                            Release_Date = new DateOnly(2000, 6, 29)
                        },
                        new
                        {
                            Id = 44,
                            Genre = "FPS",
                            Name = "Half-Life 2",
                            Opinion = "Groundbreaking narrative FPS",
                            Platform = "PC",
                            Price = 49.99f,
                            Release_Date = new DateOnly(2004, 11, 16)
                        },
                        new
                        {
                            Id = 45,
                            Genre = "Stealth",
                            Name = "Metal Gear Solid",
                            Opinion = "Cinematic stealth classic",
                            Platform = "PlayStation",
                            Price = 49.99f,
                            Release_Date = new DateOnly(1998, 9, 3)
                        },
                        new
                        {
                            Id = 46,
                            Genre = "RPG",
                            Name = "Chrono Trigger",
                            Opinion = "Timeless RPG masterpiece",
                            Platform = "SNES",
                            Price = 49.99f,
                            Release_Date = new DateOnly(1995, 3, 11)
                        },
                        new
                        {
                            Id = 47,
                            Genre = "Metroidvania",
                            Name = "Super Metroid",
                            Opinion = "Exploration masterpiece",
                            Platform = "SNES",
                            Price = 49.99f,
                            Release_Date = new DateOnly(1994, 3, 19)
                        },
                        new
                        {
                            Id = 48,
                            Genre = "Racing",
                            Name = "Mario Kart 8",
                            Opinion = "Fun multiplayer racing",
                            Platform = "Switch",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2014, 5, 29)
                        },
                        new
                        {
                            Id = 49,
                            Genre = "FPS",
                            Name = "Destiny",
                            Opinion = "Shared-world shooter",
                            Platform = "PS4",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2014, 9, 9)
                        },
                        new
                        {
                            Id = 50,
                            Genre = "Sports",
                            Name = "FIFA 18",
                            Opinion = "Popular soccer sim",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2017, 9, 29)
                        },
                        new
                        {
                            Id = 51,
                            Genre = "Fighting",
                            Name = "Mortal Kombat",
                            Opinion = "Gritty fighting classic",
                            Platform = "Arcade",
                            Price = 0.25f,
                            Release_Date = new DateOnly(1992, 10, 8)
                        },
                        new
                        {
                            Id = 52,
                            Genre = "RTS",
                            Name = "StarCraft",
                            Opinion = "Esports pioneer",
                            Platform = "PC",
                            Price = 49.99f,
                            Release_Date = new DateOnly(1998, 3, 31)
                        },
                        new
                        {
                            Id = 53,
                            Genre = "FPS",
                            Name = "Counter-Strike",
                            Opinion = "Competitive FPS legend",
                            Platform = "PC",
                            Price = 19.99f,
                            Release_Date = new DateOnly(2000, 11, 9)
                        },
                        new
                        {
                            Id = 54,
                            Genre = "Racing",
                            Name = "Gran Turismo",
                            Opinion = "Realistic racing sim",
                            Platform = "PlayStation",
                            Price = 49.99f,
                            Release_Date = new DateOnly(1997, 12, 23)
                        },
                        new
                        {
                            Id = 55,
                            Genre = "Action-Adventure",
                            Name = "Shadow of the Colossus",
                            Opinion = "Artistic masterpiece",
                            Platform = "PS2",
                            Price = 49.99f,
                            Release_Date = new DateOnly(2005, 10, 18)
                        },
                        new
                        {
                            Id = 56,
                            Genre = "Adventure",
                            Name = "Journey",
                            Opinion = "Emotional indie experience",
                            Platform = "PS3",
                            Price = 14.99f,
                            Release_Date = new DateOnly(2012, 3, 13)
                        },
                        new
                        {
                            Id = 57,
                            Genre = "Action RPG",
                            Name = "Bloodborne",
                            Opinion = "Intense gothic adventure",
                            Platform = "PS4",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2015, 3, 24)
                        },
                        new
                        {
                            Id = 58,
                            Genre = "Action-Adventure",
                            Name = "Uncharted 2: Among Thieves",
                            Opinion = "Cinematic action classic",
                            Platform = "PS3",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2009, 10, 13)
                        },
                        new
                        {
                            Id = 59,
                            Genre = "RPG",
                            Name = "Fallout: New Vegas",
                            Opinion = "Deep role-playing",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2010, 10, 19)
                        },
                        new
                        {
                            Id = 60,
                            Genre = "Platformer",
                            Name = "Celeste",
                            Opinion = "Heartfelt indie platformer",
                            Platform = "PC",
                            Price = 19.99f,
                            Release_Date = new DateOnly(2018, 1, 25)
                        },
                        new
                        {
                            Id = 61,
                            Genre = "Action-Adventure",
                            Name = "The Last of Us",
                            Opinion = "Emotional narrative masterpiece",
                            Platform = "PS3",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2013, 6, 14)
                        },
                        new
                        {
                            Id = 62,
                            Genre = "Platformer",
                            Name = "Super Mario World",
                            Opinion = "Classic Mario adventure",
                            Platform = "SNES",
                            Price = 49.99f,
                            Release_Date = new DateOnly(1990, 11, 21)
                        },
                        new
                        {
                            Id = 63,
                            Genre = "RPG",
                            Name = "Pokémon Gold/Silver",
                            Opinion = "Expanded Pokémon world",
                            Platform = "Game Boy Color",
                            Price = 39.99f,
                            Release_Date = new DateOnly(1999, 11, 21)
                        },
                        new
                        {
                            Id = 64,
                            Genre = "Sports",
                            Name = "Tony Hawk’s Pro Skater 2",
                            Opinion = "Skateboarding classic",
                            Platform = "PlayStation",
                            Price = 49.99f,
                            Release_Date = new DateOnly(2000, 9, 20)
                        },
                        new
                        {
                            Id = 65,
                            Genre = "FPS",
                            Name = "Battlefield 3",
                            Opinion = "Epic multiplayer battles",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2011, 10, 25)
                        },
                        new
                        {
                            Id = 66,
                            Genre = "Shooter",
                            Name = "Splatoon 2",
                            Opinion = "Colorful multiplayer fun",
                            Platform = "Switch",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2017, 7, 21)
                        },
                        new
                        {
                            Id = 67,
                            Genre = "Roguelike",
                            Name = "Hades",
                            Opinion = "Stylish roguelike gem",
                            Platform = "PC",
                            Price = 24.99f,
                            Release_Date = new DateOnly(2020, 9, 17)
                        },
                        new
                        {
                            Id = 68,
                            Genre = "Action-Adventure",
                            Name = "Sekiro: Shadows Die Twice",
                            Opinion = "Challenging samurai epic",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2019, 3, 22)
                        },
                        new
                        {
                            Id = 69,
                            Genre = "Action-Adventure",
                            Name = "Assassin’s Creed II",
                            Opinion = "Renaissance adventure",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2009, 11, 17)
                        },
                        new
                        {
                            Id = 70,
                            Genre = "RPG",
                            Name = "Dragon Quest XI",
                            Opinion = "Classic JRPG charm",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2018, 9, 4)
                        },
                        new
                        {
                            Id = 71,
                            Genre = "Sports",
                            Name = "Rocket League",
                            Opinion = "Soccer meets cars",
                            Platform = "PC",
                            Price = 19.99f,
                            Release_Date = new DateOnly(2015, 7, 7)
                        },
                        new
                        {
                            Id = 72,
                            Genre = "Strategy",
                            Name = "Civilization V",
                            Opinion = "Deep strategy classic",
                            Platform = "PC",
                            Price = 49.99f,
                            Release_Date = new DateOnly(2010, 9, 21)
                        },
                        new
                        {
                            Id = 73,
                            Genre = "Platformer",
                            Name = "Mega Man 2",
                            Opinion = "Iconic platformer",
                            Platform = "NES",
                            Price = 49.99f,
                            Release_Date = new DateOnly(1988, 12, 24)
                        },
                        new
                        {
                            Id = 74,
                            Genre = "Tactical RPG",
                            Name = "Fire Emblem: Three Houses",
                            Opinion = "Engaging strategy RPG",
                            Platform = "Switch",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2019, 7, 26)
                        },
                        new
                        {
                            Id = 75,
                            Genre = "Action RPG",
                            Name = "Monster Hunter: World",
                            Opinion = "Epic monster hunts",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2018, 8, 9)
                        },
                        new
                        {
                            Id = 76,
                            Genre = "Action-Adventure",
                            Name = "Tomb Raider (2013)",
                            Opinion = "Gritty reboot success",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2013, 3, 5)
                        },
                        new
                        {
                            Id = 77,
                            Genre = "Third-Person Shooter",
                            Name = "Gears of War",
                            Opinion = "Intense cover-based shooter",
                            Platform = "Xbox 360",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2006, 11, 7)
                        },
                        new
                        {
                            Id = 78,
                            Genre = "RPG",
                            Name = "Persona 5",
                            Opinion = "Stylish JRPG masterpiece",
                            Platform = "PS4",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2017, 4, 4)
                        },
                        new
                        {
                            Id = 79,
                            Genre = "Puzzle",
                            Name = "Portal 2",
                            Opinion = "Witty puzzle sequel",
                            Platform = "PC",
                            Price = 19.99f,
                            Release_Date = new DateOnly(2011, 4, 19)
                        },
                        new
                        {
                            Id = 80,
                            Genre = "Platformer",
                            Name = "Super Mario Galaxy",
                            Opinion = "Stellar 3D platformer",
                            Platform = "Wii",
                            Price = 49.99f,
                            Release_Date = new DateOnly(2007, 11, 12)
                        },
                        new
                        {
                            Id = 81,
                            Genre = "FPS",
                            Name = "Left 4 Dead",
                            Opinion = "Co-op zombie chaos",
                            Platform = "PC",
                            Price = 49.99f,
                            Release_Date = new DateOnly(2008, 11, 17)
                        },
                        new
                        {
                            Id = 82,
                            Genre = "Action-Adventure",
                            Name = "The Legend of Zelda: A Link to the Past",
                            Opinion = "Classic Zelda adventure",
                            Platform = "SNES",
                            Price = 49.99f,
                            Release_Date = new DateOnly(1991, 11, 21)
                        },
                        new
                        {
                            Id = 83,
                            Genre = "MMORPG",
                            Name = "Final Fantasy XIV",
                            Opinion = "Revived MMO success",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2013, 8, 27)
                        },
                        new
                        {
                            Id = 84,
                            Genre = "Action RPG",
                            Name = "Horizon Zero Dawn",
                            Opinion = "Stunning open-world RPG",
                            Platform = "PS4",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2017, 2, 28)
                        },
                        new
                        {
                            Id = 85,
                            Genre = "FPS",
                            Name = "Team Fortress 2",
                            Opinion = "Fun class-based shooter",
                            Platform = "PC",
                            Price = 0f,
                            Release_Date = new DateOnly(2007, 10, 10)
                        },
                        new
                        {
                            Id = 86,
                            Genre = "Puzzle",
                            Name = "Katamari Damacy",
                            Opinion = "Quirky rolling fun",
                            Platform = "PS2",
                            Price = 29.99f,
                            Release_Date = new DateOnly(2004, 3, 18)
                        },
                        new
                        {
                            Id = 87,
                            Genre = "Action-Adventure",
                            Name = "Okami",
                            Opinion = "Artistic masterpiece",
                            Platform = "PS2",
                            Price = 39.99f,
                            Release_Date = new DateOnly(2006, 4, 20)
                        },
                        new
                        {
                            Id = 88,
                            Genre = "RPG",
                            Name = "Xenoblade Chronicles",
                            Opinion = "Expansive JRPG world",
                            Platform = "Wii",
                            Price = 49.99f,
                            Release_Date = new DateOnly(2010, 6, 10)
                        },
                        new
                        {
                            Id = 89,
                            Genre = "Survival Horror",
                            Name = "Dead Space",
                            Opinion = "Terrifying sci-fi horror",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2008, 10, 14)
                        },
                        new
                        {
                            Id = 90,
                            Genre = "Action",
                            Name = "Bayonetta",
                            Opinion = "Stylish action classic",
                            Platform = "PS3",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2010, 1, 5)
                        },
                        new
                        {
                            Id = 91,
                            Genre = "MOBA",
                            Name = "Dota 2",
                            Opinion = "Competitive MOBA leader",
                            Platform = "PC",
                            Price = 0f,
                            Release_Date = new DateOnly(2013, 7, 9)
                        },
                        new
                        {
                            Id = 92,
                            Genre = "Action-Adventure",
                            Name = "Spider-Man (2018)",
                            Opinion = "Thrilling superhero adventure",
                            Platform = "PS4",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2018, 9, 7)
                        },
                        new
                        {
                            Id = 93,
                            Genre = "Fighting",
                            Name = "Super Street Fighter IV",
                            Opinion = "Refined fighting classic",
                            Platform = "PS3",
                            Price = 39.99f,
                            Release_Date = new DateOnly(2010, 4, 27)
                        },
                        new
                        {
                            Id = 94,
                            Genre = "Action RPG",
                            Name = "Nier: Automata",
                            Opinion = "Emotional action RPG",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2017, 3, 17)
                        },
                        new
                        {
                            Id = 95,
                            Genre = "Racing",
                            Name = "F-Zero",
                            Opinion = "Fast-paced futuristic racing",
                            Platform = "SNES",
                            Price = 49.99f,
                            Release_Date = new DateOnly(1990, 11, 21)
                        },
                        new
                        {
                            Id = 96,
                            Genre = "Platformer",
                            Name = "Crash Bandicoot",
                            Opinion = "Classic 90s platformer",
                            Platform = "PlayStation",
                            Price = 49.99f,
                            Release_Date = new DateOnly(1996, 9, 9)
                        },
                        new
                        {
                            Id = 97,
                            Genre = "Simulation",
                            Name = "SimCity 2000",
                            Opinion = "City-building classic",
                            Platform = "PC",
                            Price = 39.99f,
                            Release_Date = new DateOnly(1993, 1, 1)
                        },
                        new
                        {
                            Id = 98,
                            Genre = "Tower Defense",
                            Name = "Plants vs. Zombies",
                            Opinion = "Fun strategy game",
                            Platform = "PC",
                            Price = 19.99f,
                            Release_Date = new DateOnly(2009, 5, 5)
                        },
                        new
                        {
                            Id = 99,
                            Genre = "Third-Person Shooter",
                            Name = "Max Payne",
                            Opinion = "Noir action classic",
                            Platform = "PC",
                            Price = 49.99f,
                            Release_Date = new DateOnly(2001, 7, 23)
                        },
                        new
                        {
                            Id = 100,
                            Genre = "Action RPG",
                            Name = "Elden Ring",
                            Opinion = "Open-world masterpiece",
                            Platform = "PC",
                            Price = 59.99f,
                            Release_Date = new DateOnly(2022, 2, 25)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
