using System.Data;
using Microsoft.EntityFrameworkCore;
namespace GameCatalog.Models
{
    public class GameDbContext : DbContext
    {
        public GameDbContext(DbContextOptions<GameDbContext> options) : base(options) { }
        public DbSet<Game> Game { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<Game>().HasData(
                new Game { Id = 1, Name = "The Witcher 3: Wild Hunt", Genre = "RPG", Platform = "PC", Opinion = "Critically acclaimed for its story", Release_Date = new DateOnly(2015, 5, 19), Price = 59.99f },
                new Game { Id = 2, Name = "Cyberpunk 2077", Genre = "Action RPG", Platform = "PC", Opinion = "Ambitious open-world experience", Release_Date = new DateOnly(2020, 12, 10), Price = 59.99f },
                new Game { Id = 3, Name = "Dying Light", Genre = "Survival Horror", Platform = "PC", Opinion = "Thrilling zombie survival", Release_Date = new DateOnly(2015, 1, 27), Price = 49.99f },
                new Game { Id = 4, Name = "Minecraft", Genre = "Sandbox", Platform = "PC", Opinion = "Endlessly creative gameplay", Release_Date = new DateOnly(2011, 11, 18), Price = 29.99f },
                new Game { Id = 5, Name = "Grand Theft Auto V", Genre = "Action-Adventure", Platform = "PC", Opinion = "Massive open-world adventure", Release_Date = new DateOnly(2013, 9, 17), Price = 59.99f },
                new Game { Id = 6, Name = "Super Mario Bros.", Genre = "Platformer", Platform = "NES", Opinion = "Iconic platforming classic", Release_Date = new DateOnly(1985, 9, 13), Price = 49.99f },
                new Game { Id = 7, Name = "The Legend of Zelda: Ocarina of Time", Genre = "Action-Adventure", Platform = "N64", Opinion = "Timeless adventure masterpiece", Release_Date = new DateOnly(1998, 11, 21), Price = 49.99f },
                new Game { Id = 8, Name = "Tetris", Genre = "Puzzle", Platform = "Game Boy", Opinion = "Addictive and timeless", Release_Date = new DateOnly(1989, 6, 14), Price = 29.99f },
                new Game { Id = 9, Name = "Final Fantasy VII", Genre = "RPG", Platform = "PlayStation", Opinion = "Groundbreaking narrative", Release_Date = new DateOnly(1997, 9, 7), Price = 49.99f },
                new Game { Id = 10, Name = "Pokémon Red/Blue", Genre = "RPG", Platform = "Game Boy", Opinion = "Sparked a global phenomenon", Release_Date = new DateOnly(1998, 9, 28), Price = 39.99f },
                new Game { Id = 11, Name = "Super Mario 64", Genre = "Platformer", Platform = "N64", Opinion = "Revolutionary 3D platformer", Release_Date = new DateOnly(1996, 9, 26), Price = 49.99f },
                new Game { Id = 12, Name = "Halo: Combat Evolved", Genre = "FPS", Platform = "Xbox", Opinion = "Defined console shooters", Release_Date = new DateOnly(2001, 11, 15), Price = 49.99f },
                new Game { Id = 13, Name = "Wii Sports", Genre = "Sports", Platform = "Wii", Opinion = "Accessible family fun", Release_Date = new DateOnly(2006, 11, 19), Price = 49.99f },
                new Game { Id = 14, Name = "Call of Duty: Modern Warfare", Genre = "FPS", Platform = "PC", Opinion = "Set multiplayer standard", Release_Date = new DateOnly(2007, 11, 5), Price = 59.99f },
                new Game { Id = 15, Name = "The Elder Scrolls V: Skyrim", Genre = "RPG", Platform = "PC", Opinion = "Expansive fantasy world", Release_Date = new DateOnly(2011, 11, 11), Price = 59.99f },
                new Game { Id = 16, Name = "Fortnite", Genre = "Battle Royale", Platform = "PC", Opinion = "Cultural phenomenon", Release_Date = new DateOnly(2017, 7, 25), Price = 0.00f },
                new Game { Id = 17, Name = "The Legend of Zelda: Breath of the Wild", Genre = "Action-Adventure", Platform = "Switch", Opinion = "Redefined open-world games", Release_Date = new DateOnly(2017, 3, 3), Price = 59.99f },
                new Game { Id = 18, Name = "Pong", Genre = "Arcade", Platform = "Arcade", Opinion = "Pioneered video gaming", Release_Date = new DateOnly(1972, 11, 29), Price = 0.25f },
                new Game { Id = 19, Name = "Pac-Man", Genre = "Arcade", Platform = "Arcade", Opinion = "Cultural icon", Release_Date = new DateOnly(1980, 5, 22), Price = 0.25f },
                new Game { Id = 20, Name = "Donkey Kong", Genre = "Platformer", Platform = "Arcade", Opinion = "Introduced Mario", Release_Date = new DateOnly(1981, 7, 9), Price = 0.25f },
                new Game { Id = 21, Name = "Street Fighter II", Genre = "Fighting", Platform = "Arcade", Opinion = "Defined fighting games", Release_Date = new DateOnly(1991, 2, 6), Price = 0.25f },
                new Game { Id = 22, Name = "Doom", Genre = "FPS", Platform = "PC", Opinion = "Pioneered FPS genre", Release_Date = new DateOnly(1993, 12, 10), Price = 39.99f },
                new Game { Id = 23, Name = "GoldenEye 007", Genre = "FPS", Platform = "N64", Opinion = "Console FPS benchmark", Release_Date = new DateOnly(1997, 8, 25), Price = 49.99f },
                new Game { Id = 24, Name = "Super Smash Bros. Melee", Genre = "Fighting", Platform = "GameCube", Opinion = "Competitive classic", Release_Date = new DateOnly(2001, 12, 3), Price = 49.99f },
                new Game { Id = 25, Name = "Resident Evil 4", Genre = "Survival Horror", Platform = "GameCube", Opinion = "Redefined survival horror", Release_Date = new DateOnly(2005, 1, 11), Price = 49.99f },
                new Game { Id = 26, Name = "World of Warcraft", Genre = "MMORPG", Platform = "PC", Opinion = "MMO giant", Release_Date = new DateOnly(2004, 11, 23), Price = 49.99f },
                new Game { Id = 27, Name = "Guitar Hero", Genre = "Rhythm", Platform = "PS2", Opinion = "Music game revolution", Release_Date = new DateOnly(2005, 11, 8), Price = 49.99f },
                new Game { Id = 28, Name = "BioShock", Genre = "FPS", Platform = "PC", Opinion = "Immersive storytelling", Release_Date = new DateOnly(2007, 8, 21), Price = 59.99f },
                new Game { Id = 29, Name = "Portal", Genre = "Puzzle", Platform = "PC", Opinion = "Innovative puzzle design", Release_Date = new DateOnly(2007, 10, 10), Price = 19.99f },
                new Game { Id = 30, Name = "Mass Effect 2", Genre = "RPG", Platform = "PC", Opinion = "Epic sci-fi narrative", Release_Date = new DateOnly(2010, 1, 26), Price = 59.99f },
                new Game { Id = 31, Name = "Red Dead Redemption", Genre = "Action-Adventure", Platform = "PS3", Opinion = "Cinematic Western epic", Release_Date = new DateOnly(2010, 5, 18), Price = 59.99f },
                new Game { Id = 32, Name = "Batman: Arkham City", Genre = "Action-Adventure", Platform = "PC", Opinion = "Superhero perfection", Release_Date = new DateOnly(2011, 10, 18), Price = 59.99f },
                new Game { Id = 33, Name = "Dark Souls", Genre = "Action RPG", Platform = "PC", Opinion = "Challenging masterpiece", Release_Date = new DateOnly(2011, 9, 22), Price = 59.99f },
                new Game { Id = 34, Name = "League of Legends", Genre = "MOBA", Platform = "PC", Opinion = "Esports juggernaut", Release_Date = new DateOnly(2009, 10, 27), Price = 0.00f },
                new Game { Id = 35, Name = "Among Us", Genre = "Party", Platform = "PC", Opinion = "Social deduction hit", Release_Date = new DateOnly(2018, 6, 15), Price = 4.99f },
                new Game { Id = 36, Name = "Animal Crossing: New Horizons", Genre = "Simulation", Platform = "Switch", Opinion = "Charming life sim", Release_Date = new DateOnly(2020, 3, 20), Price = 59.99f },
                new Game { Id = 37, Name = "Super Mario Odyssey", Genre = "Platformer", Platform = "Switch", Opinion = "Joyful 3D platformer", Release_Date = new DateOnly(2017, 10, 27), Price = 59.99f },
                new Game { Id = 38, Name = "Overwatch", Genre = "FPS", Platform = "PC", Opinion = "Team-based shooter", Release_Date = new DateOnly(2016, 5, 24), Price = 59.99f },
                new Game { Id = 39, Name = "God of War (2018)", Genre = "Action-Adventure", Platform = "PS4", Opinion = "Emotional epic", Release_Date = new DateOnly(2018, 4, 20), Price = 59.99f },
                new Game { Id = 40, Name = "Hollow Knight", Genre = "Metroidvania", Platform = "PC", Opinion = "Atmospheric indie gem", Release_Date = new DateOnly(2017, 2, 24), Price = 14.99f },
                new Game { Id = 41, Name = "Stardew Valley", Genre = "Simulation", Platform = "PC", Opinion = "Charming farming sim", Release_Date = new DateOnly(2016, 2, 26), Price = 14.99f },
                new Game { Id = 42, Name = "The Sims", Genre = "Simulation", Platform = "PC", Opinion = "Life simulation classic", Release_Date = new DateOnly(2000, 2, 4), Price = 49.99f },
                new Game { Id = 43, Name = "Diablo II", Genre = "Action RPG", Platform = "PC", Opinion = "Addictive loot-driven RPG", Release_Date = new DateOnly(2000, 6, 29), Price = 49.99f },
                new Game { Id = 44, Name = "Half-Life 2", Genre = "FPS", Platform = "PC", Opinion = "Groundbreaking narrative FPS", Release_Date = new DateOnly(2004, 11, 16), Price = 49.99f },
                new Game { Id = 45, Name = "Metal Gear Solid", Genre = "Stealth", Platform = "PlayStation", Opinion = "Cinematic stealth classic", Release_Date = new DateOnly(1998, 9, 3), Price = 49.99f },
                new Game { Id = 46, Name = "Chrono Trigger", Genre = "RPG", Platform = "SNES", Opinion = "Timeless RPG masterpiece", Release_Date = new DateOnly(1995, 3, 11), Price = 49.99f },
                new Game { Id = 47, Name = "Super Metroid", Genre = "Metroidvania", Platform = "SNES", Opinion = "Exploration masterpiece", Release_Date = new DateOnly(1994, 3, 19), Price = 49.99f },
                new Game { Id = 48, Name = "Mario Kart 8", Genre = "Racing", Platform = "Switch", Opinion = "Fun multiplayer racing", Release_Date = new DateOnly(2014, 5, 29), Price = 59.99f },
                new Game { Id = 49, Name = "Destiny", Genre = "FPS", Platform = "PS4", Opinion = "Shared-world shooter", Release_Date = new DateOnly(2014, 9, 9), Price = 59.99f },
                new Game { Id = 50, Name = "FIFA 18", Genre = "Sports", Platform = "PC", Opinion = "Popular soccer sim", Release_Date = new DateOnly(2017, 9, 29), Price = 59.99f },
                new Game { Id = 51, Name = "Mortal Kombat", Genre = "Fighting", Platform = "Arcade", Opinion = "Gritty fighting classic", Release_Date = new DateOnly(1992, 10, 8), Price = 0.25f },
                new Game { Id = 52, Name = "StarCraft", Genre = "RTS", Platform = "PC", Opinion = "Esports pioneer", Release_Date = new DateOnly(1998, 3, 31), Price = 49.99f },
                new Game { Id = 53, Name = "Counter-Strike", Genre = "FPS", Platform = "PC", Opinion = "Competitive FPS legend", Release_Date = new DateOnly(2000, 11, 9), Price = 19.99f },
                new Game { Id = 54, Name = "Gran Turismo", Genre = "Racing", Platform = "PlayStation", Opinion = "Realistic racing sim", Release_Date = new DateOnly(1997, 12, 23), Price = 49.99f },
                new Game { Id = 55, Name = "Shadow of the Colossus", Genre = "Action-Adventure", Platform = "PS2", Opinion = "Artistic masterpiece", Release_Date = new DateOnly(2005, 10, 18), Price = 49.99f },
                new Game { Id = 56, Name = "Journey", Genre = "Adventure", Platform = "PS3", Opinion = "Emotional indie experience", Release_Date = new DateOnly(2012, 3, 13), Price = 14.99f },
                new Game { Id = 57, Name = "Bloodborne", Genre = "Action RPG", Platform = "PS4", Opinion = "Intense gothic adventure", Release_Date = new DateOnly(2015, 3, 24), Price = 59.99f },
                new Game { Id = 58, Name = "Uncharted 2: Among Thieves", Genre = "Action-Adventure", Platform = "PS3", Opinion = "Cinematic action classic", Release_Date = new DateOnly(2009, 10, 13), Price = 59.99f },
                new Game { Id = 59, Name = "Fallout: New Vegas", Genre = "RPG", Platform = "PC", Opinion = "Deep role-playing", Release_Date = new DateOnly(2010, 10, 19), Price = 59.99f },
                new Game { Id = 60, Name = "Celeste", Genre = "Platformer", Platform = "PC", Opinion = "Heartfelt indie platformer", Release_Date = new DateOnly(2018, 1, 25), Price = 19.99f },
                new Game { Id = 61, Name = "The Last of Us", Genre = "Action-Adventure", Platform = "PS3", Opinion = "Emotional narrative masterpiece", Release_Date = new DateOnly(2013, 6, 14), Price = 59.99f },
                new Game { Id = 62, Name = "Super Mario World", Genre = "Platformer", Platform = "SNES", Opinion = "Classic Mario adventure", Release_Date = new DateOnly(1990, 11, 21), Price = 49.99f },
                new Game { Id = 63, Name = "Pokémon Gold/Silver", Genre = "RPG", Platform = "Game Boy Color", Opinion = "Expanded Pokémon world", Release_Date = new DateOnly(1999, 11, 21), Price = 39.99f },
                new Game { Id = 64, Name = "Tony Hawk’s Pro Skater 2", Genre = "Sports", Platform = "PlayStation", Opinion = "Skateboarding classic", Release_Date = new DateOnly(2000, 9, 20), Price = 49.99f },
                new Game { Id = 65, Name = "Battlefield 3", Genre = "FPS", Platform = "PC", Opinion = "Epic multiplayer battles", Release_Date = new DateOnly(2011, 10, 25), Price = 59.99f },
                new Game { Id = 66, Name = "Splatoon 2", Genre = "Shooter", Platform = "Switch", Opinion = "Colorful multiplayer fun", Release_Date = new DateOnly(2017, 7, 21), Price = 59.99f },
                new Game { Id = 67, Name = "Hades", Genre = "Roguelike", Platform = "PC", Opinion = "Stylish roguelike gem", Release_Date = new DateOnly(2020, 9, 17), Price = 24.99f },
                new Game { Id = 68, Name = "Sekiro: Shadows Die Twice", Genre = "Action-Adventure", Platform = "PC", Opinion = "Challenging samurai epic", Release_Date = new DateOnly(2019, 3, 22), Price = 59.99f },
                new Game { Id = 69, Name = "Assassin’s Creed II", Genre = "Action-Adventure", Platform = "PC", Opinion = "Renaissance adventure", Release_Date = new DateOnly(2009, 11, 17), Price = 59.99f },
                new Game { Id = 70, Name = "Dragon Quest XI", Genre = "RPG", Platform = "PC", Opinion = "Classic JRPG charm", Release_Date = new DateOnly(2018, 9, 4), Price = 59.99f },
                new Game { Id = 71, Name = "Rocket League", Genre = "Sports", Platform = "PC", Opinion = "Soccer meets cars", Release_Date = new DateOnly(2015, 7, 7), Price = 19.99f },
                new Game { Id = 72, Name = "Civilization V", Genre = "Strategy", Platform = "PC", Opinion = "Deep strategy classic", Release_Date = new DateOnly(2010, 9, 21), Price = 49.99f },
                new Game { Id = 73, Name = "Mega Man 2", Genre = "Platformer", Platform = "NES", Opinion = "Iconic platformer", Release_Date = new DateOnly(1988, 12, 24), Price = 49.99f },
                new Game { Id = 74, Name = "Fire Emblem: Three Houses", Genre = "Tactical RPG", Platform = "Switch", Opinion = "Engaging strategy RPG", Release_Date = new DateOnly(2019, 7, 26), Price = 59.99f },
                new Game { Id = 75, Name = "Monster Hunter: World", Genre = "Action RPG", Platform = "PC", Opinion = "Epic monster hunts", Release_Date = new DateOnly(2018, 8, 9), Price = 59.99f },
                new Game { Id = 76, Name = "Tomb Raider (2013)", Genre = "Action-Adventure", Platform = "PC", Opinion = "Gritty reboot success", Release_Date = new DateOnly(2013, 3, 5), Price = 59.99f },
                new Game { Id = 77, Name = "Gears of War", Genre = "Third-Person Shooter", Platform = "Xbox 360", Opinion = "Intense cover-based shooter", Release_Date = new DateOnly(2006, 11, 7), Price = 59.99f },
                new Game { Id = 78, Name = "Persona 5", Genre = "RPG", Platform = "PS4", Opinion = "Stylish JRPG masterpiece", Release_Date = new DateOnly(2017, 4, 4), Price = 59.99f },
                new Game { Id = 79, Name = "Portal 2", Genre = "Puzzle", Platform = "PC", Opinion = "Witty puzzle sequel", Release_Date = new DateOnly(2011, 4, 19), Price = 19.99f },
                new Game { Id = 80, Name = "Super Mario Galaxy", Genre = "Platformer", Platform = "Wii", Opinion = "Stellar 3D platformer", Release_Date = new DateOnly(2007, 11, 12), Price = 49.99f },
                new Game { Id = 81, Name = "Left 4 Dead", Genre = "FPS", Platform = "PC", Opinion = "Co-op zombie chaos", Release_Date = new DateOnly(2008, 11, 17), Price = 49.99f },
                new Game { Id = 82, Name = "The Legend of Zelda: A Link to the Past", Genre = "Action-Adventure", Platform = "SNES", Opinion = "Classic Zelda adventure", Release_Date = new DateOnly(1991, 11, 21), Price = 49.99f },
                new Game { Id = 83, Name = "Final Fantasy XIV", Genre = "MMORPG", Platform = "PC", Opinion = "Revived MMO success", Release_Date = new DateOnly(2013, 8, 27), Price = 59.99f },
                new Game { Id = 84, Name = "Horizon Zero Dawn", Genre = "Action RPG", Platform = "PS4", Opinion = "Stunning open-world RPG", Release_Date = new DateOnly(2017, 2, 28), Price = 59.99f },
                new Game { Id = 85, Name = "Team Fortress 2", Genre = "FPS", Platform = "PC", Opinion = "Fun class-based shooter", Release_Date = new DateOnly(2007, 10, 10), Price = 0.00f },
                new Game { Id = 86, Name = "Katamari Damacy", Genre = "Puzzle", Platform = "PS2", Opinion = "Quirky rolling fun", Release_Date = new DateOnly(2004, 3, 18), Price = 29.99f },
                new Game { Id = 87, Name = "Okami", Genre = "Action-Adventure", Platform = "PS2", Opinion = "Artistic masterpiece", Release_Date = new DateOnly(2006, 4, 20), Price = 39.99f },
                new Game { Id = 88, Name = "Xenoblade Chronicles", Genre = "RPG", Platform = "Wii", Opinion = "Expansive JRPG world", Release_Date = new DateOnly(2010, 6, 10), Price = 49.99f },
                new Game { Id = 89, Name = "Dead Space", Genre = "Survival Horror", Platform = "PC", Opinion = "Terrifying sci-fi horror", Release_Date = new DateOnly(2008, 10, 14), Price = 59.99f },
                new Game { Id = 90, Name = "Bayonetta", Genre = "Action", Platform = "PS3", Opinion = "Stylish action classic", Release_Date = new DateOnly(2010, 1, 5), Price = 59.99f },
                new Game { Id = 91, Name = "Dota 2", Genre = "MOBA", Platform = "PC", Opinion = "Competitive MOBA leader", Release_Date = new DateOnly(2013, 7, 9), Price = 0.00f },
                new Game { Id = 92, Name = "Spider-Man (2018)", Genre = "Action-Adventure", Platform = "PS4", Opinion = "Thrilling superhero adventure", Release_Date = new DateOnly(2018, 9, 7), Price = 59.99f },
                new Game { Id = 93, Name = "Super Street Fighter IV", Genre = "Fighting", Platform = "PS3", Opinion = "Refined fighting classic", Release_Date = new DateOnly(2010, 4, 27), Price = 39.99f },
                new Game { Id = 94, Name = "Nier: Automata", Genre = "Action RPG", Platform = "PC", Opinion = "Emotional action RPG", Release_Date = new DateOnly(2017, 3, 17), Price = 59.99f },
                new Game { Id = 95, Name = "F-Zero", Genre = "Racing", Platform = "SNES", Opinion = "Fast-paced futuristic racing", Release_Date = new DateOnly(1990, 11, 21), Price = 49.99f },
                new Game { Id = 96, Name = "Crash Bandicoot", Genre = "Platformer", Platform = "PlayStation", Opinion = "Classic 90s platformer", Release_Date = new DateOnly(1996, 9, 9), Price = 49.99f },
                new Game { Id = 97, Name = "SimCity 2000", Genre = "Simulation", Platform = "PC", Opinion = "City-building classic", Release_Date = new DateOnly(1993, 1, 1), Price = 39.99f },
                new Game { Id = 98, Name = "Plants vs. Zombies", Genre = "Tower Defense", Platform = "PC", Opinion = "Fun strategy game", Release_Date = new DateOnly(2009, 5, 5), Price = 19.99f },
                new Game { Id = 99, Name = "Max Payne", Genre = "Third-Person Shooter", Platform = "PC", Opinion = "Noir action classic", Release_Date = new DateOnly(2001, 7, 23), Price = 49.99f },
                new Game { Id = 100, Name = "Elden Ring", Genre = "Action RPG", Platform = "PC", Opinion = "Open-world masterpiece", Release_Date = new DateOnly(2022, 2, 25), Price = 59.99f }
            );
        }
    }
}
